export const WEB3_AUTH_SUCCESS = "WEB3_AUTH_SUCCESS";
export const WEB3_AUTH_FAIL = "WEB3_AUTH_FAIL";

export const SET_UNIBEARS_COUNT = 'SET_UNIBEARS_COUNT';

export const LECTURE_CHANGE = "LECTURE_CHANGE";

export const UPDATE_PREVIOUS_AND_NEXT_LECTURE = "UPDATE_PREVIOUS_AND_NEXT_LECTURE";
