export const WEB3_AUTH_SUCCESS = "WEB3_AUTH_SUCCESS";
export const WEB3_AUTH_FAIL = "WEB3_AUTH_FAIL";

export const UNIBEARS_COUNT_REQUEST_SUCCESS = "UNIBEARS_COUNT_REQUEST_SUCCESS";
export const UNIBEARS_COUNT_REQUEST_FAIL = "UNIBEARS_COUNT_REQUEST_FAIL";

export const LECTURE_CHANGE = "LECTURE_CHANGE";

export const UPDATE_PREVIOUS_AND_NEXT_LECTURE =
  "UPDATE_PREVIOUS_AND_NEXT_LECTURE";
